apiVersion: v1
kind: Service
metadata:
  name: nowaitech-service
  namespace: default
spec:
  selector:
    app: web-front
  type: LoadBalancer
  ports:
  - name: nowaitech-port
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: default
  labels:
    app: web-front
spec:
  selector:
    matchLabels:
      app: web-front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
      - name: nowaitech-web
        image: cansentay/nowaitech
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: web-storage
          mountPath: "/usr/share/nginx/html"
      volumes:
        - name: web-storage
          emptyDir: {}
      imagePullSecrets:
      - name: mysecret
